export const SKILLS = [
  {
    id: "ai-automation",
    title: "AI Automation",
    img: "/images/one.jpg",
    desc: "Experience the power of intelligent workflows that handle repetitive tasks with precision.",
    details: "This comprehensive course dives deep into the world of AI-driven automation, equipping you with the tools to transform traditional business processes. You will start by mastering the fundamentals of workflow optimization and Robotic Process Automation (RPA), learning how to identify and automate high-impact, repetitive tasks. The curriculum explores advanced integration strategies, showing you how to seamlessly embed AI models into existing enterprise ecosystems. You will gain hands-on experience building custom automation scripts that handle data processing, customer engagement, and complex decision-making logic. Beyond technical implementation, the course addresses the critical ethical implications of automation, preparing you to lead responsible transformations in the modern workforce. By the end of the program, you will have developed a portfolio of functional automation projects that demonstrate your ability to scale efficiency and reduce human error across diverse industries. This path is perfect for those looking to stay ahead in the rapidly evolving landscape of intelligent systems.",
    rating: "4.9",
    color: "from-blue-500/20",
    glow: "shadow-blue-500/20",
  },
  {
    id: "ai-chatbot",
    title: "AI Chatbot",
    img: "/images/two.jpg",
    desc: "Engage your audience like never before with next-generation conversational agents.",
    details: "Step into the future of communication by learning to design and deploy sophisticated AI chatbots from the ground up. This course provides a masterclass in Natural Language Processing (NLP), teaching you how to train models that understand context, sentiment, and user intent with remarkable accuracy. You will explore the intricacies of dialogue management, learning how to create fluid, non-linear conversations that provide genuine value to users. The program covers multi-platform deployment, ensuring your agents can live on the web, mobile apps, and popular social media interfaces simultaneously. You will work with state-of-the-art LLM (Large Language Model) APIs, fine-tuning them for specific industry use cases like customer support, e-commerce, and personalized advisory. We also delve into the technical infrastructure required for real-time response handling and database integration. By completing this course, you will be capable of building enterprise-grade conversational interfaces that drive engagement and automate complex user inquiries without sacrificing the human touch.",
    rating: "4.8",
    color: "from-purple-500/20",
    glow: "shadow-purple-500/20",
  },
  {
    id: "ai-video-creation",
    title: "AI Video Creation",
    img: "/images/three.jpg",
    desc: "Unleash your creativity with generative media tools that turn ideas into cinematic reality.",
    details: "Unleash the next dimension of digital storytelling by mastering the cutting-edge tools of generative video production. This course takes you on a journey through the entire AI media pipeline, from initial script generation to final cinematic rendering. You will learn to use sophisticated text-to-video models to create high-quality visual content from simple prompts, dramatically reducing production times. The curriculum includes deep dives into advanced character animation, face-swapping (focused on ethical application), and automated video editing techniques. You'll master the art of fine-tuning generative models to maintain visual consistency across scenes, a critical skill for long-form narrative content. We also cover professional audio synchronization and AI-driven color grading to ensure your outputs meet industry standards. Whether you're a filmmaker, marketer, or content creator, this course provides the technical expertise to produce stunning, high-fidelity video assets with minimal manual overhead. Prepare to revolutionize your creative workflow and lead the charge in the generative media revolution.",
    rating: "4.7",
    color: "from-pink-500/20",
    glow: "shadow-pink-500/20",
  },
  {
    id: "website-development",
    title: "Website Development",
    img: "/images/four.jpg",
    desc: "Build the foundation of your digital presence with high-performance, responsive web applications.",
    details: "Build the modern web with a comprehensive curriculum that bridges the gap between traditional development and AI-enhanced productivity. This intensive program covers the entire stack, starting with rock-solid HTML5 and CSS3 fundamentals before moving into advanced JavaScript architectures. You will master the React ecosystem and Next.js, learning how to build lightning-fast, SEO-optimized applications that can scale to millions of users. A key highlight of this course is the integration of AI coding assistants and testing tools, teaching you how to multiply your output and significantly reduce bugs. You'll explore responsive design systems, performance optimization techniques like server-side rendering, and secure API management. The course also includes modules on modern deployment pipelines and cloud infrastructure management. By the end of this track, you will have the skills to architect and build full-featured, AI-powered web platforms that meet the rigorous demands of today's tech industry. It's time to transition from a coder to a full-stack architect capable of delivering unparalleled digital experiences.",
    rating: "4.9",
    color: "from-green-500/20",
    glow: "shadow-green-500/20",
  },
  {
    id: "blockchain-development",
    title: "Blockchain Development",
    img: "/images/two.jpg",
    desc: "Enter the world of decentralized technology with secure, transparent, and immutable solutions.",
    details: "Join the forefront of the decentralized revolution by mastering the core architectures and practical applications of blockchain technology. This course provides an in-depth exploration of the Ethereum ecosystem, teaching you to write secure, efficient smart contracts using Solidity. You will learn the fundamentals of cryptography, consensus mechanisms, and the economic principles that drive decentralized finance (DeFi). The curriculum guides you through the process of building full-featured Decentralized Applications (DApps), from frontend integration with Web3 libraries to backend on-chain logic. You will focus heavily on security best practices, learning how to audit your code and protect against common vulnerabilities like reentrancy attacks. We also explore the emerging landscapes of NFTs, DAOs, and Layer-2 scaling solutions. Whether you're interested in revamping global finance or building transparent governance systems, this course gives you the technical foundation to build immutable, trustless solutions that will define the next era of the internet. Prepare to become a certified pioneer in the world of Web3 and decentralized infrastructure.",
    rating: "4.8",
    color: "from-orange-500/20",
    glow: "shadow-orange-500/20",
  },
];
