-- ============================================================
-- SQL Migration: Tech Courses and Tech Staff Tables
-- Run this in your Supabase project's SQL Editor
-- ============================================================

-- 1. Tech Courses Table 
-- To manage different tech subjects added to different classes
CREATE TABLE IF NOT EXISTS tech_courses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  class_name text NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- 2. Tech Course IDs Table 
-- To manage unique ID assignments generated by Admin
CREATE TABLE IF NOT EXISTS tech_course_ids (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tech_course_id uuid REFERENCES tech_courses(id) ON DELETE CASCADE,
  external_id text NOT NULL,
  class_name text NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- 3. Tech Teachers Table 
-- To handle Tech Staff login profiles
CREATE TABLE IF NOT EXISTS tech_teachers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  cclass text NOT NULL,
  course text NOT NULL,
  email text NOT NULL UNIQUE,
  course_id text NOT NULL UNIQUE,
  password text NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- Turn off Row Level Security (RLS) for Development simplicity
ALTER TABLE tech_courses DISABLE ROW LEVEL SECURITY;
ALTER TABLE tech_course_ids DISABLE ROW LEVEL SECURITY;
ALTER TABLE tech_teachers DISABLE ROW LEVEL SECURITY;
